spring:
  application:
    name: library
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/library
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

static:
  images:
    realPath: P:/ServerData/library/static/
#    serverPath: